package com.amfam.demos.approvals;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Weather implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "City ID")
   private java.lang.Integer cityId;
   @org.kie.api.definition.type.Label(value = "City Name")
   private java.lang.Integer cityName;
   @org.kie.api.definition.type.Label(value = "City Country")
   private java.lang.String cityCountry;
   @org.kie.api.definition.type.Label(value = "Temperature Value")
   private java.math.BigDecimal temperatureValue;
   @org.kie.api.definition.type.Label(value = "Wind Speed")
   private java.math.BigDecimal windSpeed;

   public Weather()
   {
   }

   public java.lang.Integer getCityId()
   {
      return this.cityId;
   }

   public void setCityId(java.lang.Integer cityId)
   {
      this.cityId = cityId;
   }

   public java.lang.Integer getCityName()
   {
      return this.cityName;
   }

   public void setCityName(java.lang.Integer cityName)
   {
      this.cityName = cityName;
   }

   public java.lang.String getCityCountry()
   {
      return this.cityCountry;
   }

   public void setCityCountry(java.lang.String cityCountry)
   {
      this.cityCountry = cityCountry;
   }

   public java.math.BigDecimal getTemperatureValue()
   {
      return this.temperatureValue;
   }

   public void setTemperatureValue(java.math.BigDecimal temperatureValue)
   {
      this.temperatureValue = temperatureValue;
   }

   public java.math.BigDecimal getWindSpeed()
   {
      return this.windSpeed;
   }

   public void setWindSpeed(java.math.BigDecimal windSpeed)
   {
      this.windSpeed = windSpeed;
   }

   public Weather(java.lang.Integer cityId, java.lang.Integer cityName,
         java.lang.String cityCountry,
         java.math.BigDecimal temperatureValue,
         java.math.BigDecimal windSpeed)
   {
      this.cityId = cityId;
      this.cityName = cityName;
      this.cityCountry = cityCountry;
      this.temperatureValue = temperatureValue;
      this.windSpeed = windSpeed;
   }

}